apiVersion: v1
kind: Pod
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  containers:
    - name: mongo
      image: mongo:6
      ports:
        - containerPort: 27017
      env:
        - name: MONGO_INITDB_DATABASE
          value: todo_db
      volumeMounts:
        - name: mongo-data
          mountPath: /data/db
  volumes:
    - name: mongo-data
      emptyDir: {}   # Temporary storage for development

